
import { Attendance } from "@/types";

export const mockAttendance: Attendance[] = [
  {
    id: "attendance-1",
    classId: "class-1",
    className: "CSE-101-A-2023",
    date: "2023-09-05",
    studentId: "user-4",
    studentName: "Rakib Ahmed",
    status: "present",
  },
  {
    id: "attendance-2",
    classId: "class-1",
    className: "CSE-101-A-2023",
    date: "2023-09-05",
    studentId: "user-5",
    studentName: "Saima Khan",
    status: "present",
  },
  {
    id: "attendance-3",
    classId: "class-1",
    className: "CSE-101-A-2023",
    date: "2023-09-05",
    studentId: "user-8",
    studentName: "Mohammad Ali",
    status: "absent",
  },
  {
    id: "attendance-4",
    classId: "class-3",
    className: "EEE-101-A-2023",
    date: "2023-09-05",
    studentId: "user-6",
    studentName: "Karim Rahman",
    status: "present",
  },
  {
    id: "attendance-5",
    classId: "class-3",
    className: "EEE-101-A-2023",
    date: "2023-09-05",
    studentId: "user-7",
    studentName: "Nusrat Jahan",
    status: "late",
  },
  {
    id: "attendance-6",
    classId: "class-1",
    className: "CSE-101-A-2023",
    date: "2023-09-07",
    studentId: "user-4",
    studentName: "Rakib Ahmed",
    status: "present",
  },
  {
    id: "attendance-7",
    classId: "class-1",
    className: "CSE-101-A-2023",
    date: "2023-09-07",
    studentId: "user-5",
    studentName: "Saima Khan",
    status: "absent",
  },
  {
    id: "attendance-8",
    classId: "class-1",
    className: "CSE-101-A-2023",
    date: "2023-09-07",
    studentId: "user-8",
    studentName: "Mohammad Ali",
    status: "present",
  },
];
