
import { Class } from "@/types";

export const mockClasses: Class[] = [
  {
    id: "class-1",
    departmentId: "dept-4",
    departmentCode: "CSE",
    courseId: "course-1",
    courseCode: "CSE-101",
    courseName: "Introduction to Computer Science",
    session: "2023-24",
    section: "A",
    code: "CSE-101-A-2023",
    teacherId: "user-2",
    teacherName: "Dr. Khalid Hassan",
  },
  {
    id: "class-2",
    departmentId: "dept-4",
    departmentCode: "CSE",
    courseId: "course-2",
    courseCode: "CSE-102",
    courseName: "Structured Programming",
    session: "2023-24",
    section: "A",
    code: "CSE-102-A-2023",
    teacherId: "user-9",
    teacherName: "Dr. Rahim Uddin",
  },
  {
    id: "class-3",
    departmentId: "dept-2",
    departmentCode: "EEE",
    courseId: "course-5",
    courseCode: "EEE-101",
    courseName: "Electrical Circuits I",
    session: "2023-24",
    section: "A",
    code: "EEE-101-A-2023",
    teacherId: "user-3",
    teacherName: "Dr. Fahmida Akter",
  },
  {
    id: "class-4",
    departmentId: "dept-2",
    departmentCode: "EEE",
    courseId: "course-6",
    courseCode: "EEE-102",
    courseName: "Electrical Circuits II",
    session: "2023-24",
    section: "B",
    code: "EEE-102-B-2023",
    teacherId: "user-10",
    teacherName: "Dr. Tasneem Akter",
  },
  {
    id: "class-5",
    departmentId: "dept-4",
    departmentCode: "CSE",
    courseId: "course-3",
    courseCode: "CSE-201",
    courseName: "Data Structures",
    session: "2022-23",
    section: "A",
    code: "CSE-201-A-2022",
    teacherId: "user-2",
    teacherName: "Dr. Khalid Hassan",
  },
  {
    id: "class-6",
    departmentId: "dept-2",
    departmentCode: "EEE",
    courseId: "course-7",
    courseCode: "EEE-201",
    courseName: "Electronics I",
    session: "2022-23",
    section: "A",
    code: "EEE-201-A-2022",
    teacherId: "user-3",
    teacherName: "Dr. Fahmida Akter",
  },
];
