
import { User } from "@/types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Admin User",
    email: "admin@cuet.ac.bd",
    role: "admin",
  },
  {
    id: "user-2",
    name: "Dr. Khalid Hassan",
    email: "khalid@cuet.ac.bd",
    role: "teacher",
    department: "04 - Computer Science and Engineering",
  },
  {
    id: "user-3",
    name: "Dr. Fahmida Akter",
    email: "fahmida@cuet.ac.bd",
    role: "teacher",
    department: "02 - Electrical and Electronic Engineering",
  },
  {
    id: "user-4",
    name: "Rakib Ahmed",
    email: "u2109012@student.cuet.ac.bd",
    role: "student",
    department: "04 - Computer Science and Engineering",
    session: "2021-22",
    section: "A",
    isClassRepresentative: true,
  },
  {
    id: "user-5",
    name: "Saima Khan",
    email: "u2109034@student.cuet.ac.bd",
    role: "student",
    department: "04 - Computer Science and Engineering",
    session: "2021-22",
    section: "A",
  },
  {
    id: "user-6",
    name: "Karim Rahman",
    email: "u2208008@student.cuet.ac.bd",
    role: "student",
    department: "02 - Electrical and Electronic Engineering",
    session: "2022-23",
    section: "B",
  },
  {
    id: "user-7",
    name: "Nusrat Jahan",
    email: "u2208015@student.cuet.ac.bd",
    role: "student",
    department: "02 - Electrical and Electronic Engineering",
    session: "2022-23",
    section: "A",
    isClassRepresentative: true,
  },
  {
    id: "user-8",
    name: "Mohammad Ali",
    email: "u2109045@student.cuet.ac.bd",
    role: "student",
    department: "04 - Computer Science and Engineering",
    session: "2021-22",
    section: "B",
  },
  {
    id: "user-9",
    name: "Dr. Rahim Uddin",
    email: "rahim@cuet.ac.bd",
    role: "teacher",
    department: "04 - Computer Science and Engineering",
  },
  {
    id: "user-10",
    name: "Dr. Tasneem Akter",
    email: "tasneem@cuet.ac.bd",
    role: "teacher",
    department: "02 - Electrical and Electronic Engineering",
  },
];
