// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jliuipslcprhvgheozuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsaXVpcHNsY3ByaHZnaGVvenVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NTE1ODAsImV4cCI6MjA1NDIyNzU4MH0.V3Fp3z0DdNW6aoWP2cIZ8c_OVsJPNCRZqfpNlwHOB90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);